name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - os: macos-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.13"

    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          create-args: >-
            python={% raw %}${{ matrix.python-version }}{% endraw %}
            pip

      - name: install dependencies
        run: pip install tox tox-gh-actions

      - name: test with tox
        run: tox
        env:
          CONDA_EXE: mamba

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}

      - name: list files
        run: ls -l .
